### ISSUE TITLE
Cookie handling cannot be disabled since v3.2.1

### ISSUE THREAD

**Issue by alex-schneider** [m6w6/ext-http#89] opened 2019-07-10 10:33 UTC
The workaround for #84 enables cookies for the entire session and cannot be deactivated if connection-reuse is enabled.

Commit https://github.com/m6w6/ext-http/commit/301589da4272ff7b2e3de6764f7c6290907a1a6b sets `curl_easy_setopt(handler->handle, CURLOPT_COOKIEJAR, NULL)`

According to https://curl.haxx.se/libcurl/c/CURLOPT_COOKIEJAR.html : Using this option also enables cookies for this session, so if you for example follow a location it will make matching cookies get sent accordingly.

We need to handle cookies ourselves, because we handle multiple concurrent sessions and want to use persistent connections for performance reasons.

**Comment by rcanavan** [comment] 2019-07-10 13:39
This was broken before and has been fixed  in #36.

**Comment by m6w6** [comment] 2019-07-10 18:51
We should probably limit that workaround to affected libcurl versions.

**Comment by m6w6** [comment] 2019-07-12 12:29
Can you provide a test case so this will not happen again?

The current test suite does not show any differences except avoiding the crashes with libcurl 7.63-7.64, even the new tests committed in https://github.com/m6w6/ext-http/commit/70b33dfb356cc2792bbec57995f7ce687ae8f16d

**Closed** 2021-01-13 09:37 UTC
Labels: regression

**Comment by afflerbach** [comment] 2023-02-01 08:27
Two years later… 

… I can confirm, that the issue is gone (at least in release 4.2.3). Thank you!  :+1:

**Comment by m6w6** [comment] 2023-02-01 11:03
"Thumbs up" is always good to hear and never too late! Thanks,
