### ISSUE TITLE
$http->setSslOptions() notice w/ curl 7.43

### ISSUE THREAD

**Issue by recipe** [m6w6/ext-http#20] opened 2016-01-21 12:55 UTC
#### Description
When we try to execute this code:
```php
<?php
error_reporting(E_ALL);
ini_set('display_errors', true);

$req = new \http\Client\Request("GET", "http://google.com");

$req->setOptions([
    'redirect'       => 10,
    'timeout'        => 30,
    'connecttimeout' => 30,
    'cookiesession'  => true,
]);

$req->setSslOptions([
    'verifypeer' => false,
    'verifyhost' => false
]);

$response = (new \http\Client())->enqueue($req)->send()->getResponse($req);

var_dump($response->getBody()->toString());
```

It barks with notices:
```
Notice: http\Client::enqueue(): Could not set option verifystatus (No error) in /Users/igor/Sites/scalr/test.php on line 20

Notice: http\Client::enqueue(): Could not set option ssl (No error) in /Users/igor/Sites/scalr/test.php on line 20
```

#### System info
```bash
$ php -i | grep -i -A1 "http support"
HTTP Support => enabled
Extension Version => 2.5.5

$ php -i | grep -i "libcurl"
libcurl => 7.43.0 => 7.43.0

$ curl -V
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 

$ php -v
PHP 5.6.16 (cli) (built: Nov 27 2015 10:28:34) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

**Comment by m6w6** [comment] 2016-01-21 13:47
Hm... cannot reproduce at a quick glance.

What's your OS?
Where does your PHP come from? (install method)
Where's pecl_http from? (install method)
Where's your libcurl from? (install method)

Thanks!

**Comment by m6w6** [comment] 2016-01-21 13:49
Ah, that actually may be due to a different SSL lib. What SSL library is your libcurl linked against?

    ldd /usr/lib/libcurl.so

**Comment by m6w6** [comment] 2016-01-21 13:56
If you're familiar with building pecl_http yourself, you could try the following patch to verify a possible fix:
[issue20.txt](https://github.com/m6w6/ext-http/files/99199/issue20.txt)

It would still be interesting to know your SSL library used by libcurl.

Thanks.

**Comment by recipe** [comment] 2016-01-21 16:24
It's macbook pro 10.11.3 (15D21).

```
$ uname -a
Darwin dhcp245.office.webta 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64

OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.2d 9 Jul 2015
OpenSSL Header Version => OpenSSL 1.0.2d 9 Jul 2015
```

PHP was installed via `homebrew`

pecl_http was installed by pecl

Pear was installed by:
```
$ wget http://pear.php.net/go-pear.phar
$ php go-pear.phar
```

libcurl came with system.

**Comment by m6w6** [comment] 2016-01-21 16:33
Thanks for the report! 

The fix will be in the next release. Apply the patch mentioned above if you want to get rid of the notice in the meantime.

**Closed** 2016-01-21 16:32 UTC
Labels: in progress
